name: Test Install
on:
  workflow_dispatch:
  # remove branch when merged
  push:
    branches:
      - windows-setup
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.8]
    name: Python ${{ matrix.python-version }} Installation for Synthpop ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Use Default python to install
        run: | 
          python --version
          which python
          conda create -n myenv python=3
          conda activate myenv
          python setup.py develop
      
      #- name: Use Conda to install
      #  uses: s-weigand/setup-conda@v1
      #  with:
      #    update-conda: true
      #    python-version: ${{ matrix.python-version }}
      #    conda-channels: anaconda, conda-forge
      #- run: conda --version
      #- run: which python
      #- run: python setup.py develop
      
     
