name: Synthpops CI workflow
on: [pull_request]

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        python-version: [ '3.7' ]
    name: Install and test
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install synthpops
        run: python setup.py develop
      - name: Install tests
        run: pip install -r tests/requirements_test.txt
      - name: Run API tests
        working-directory: ./tests
        run:  coverage run --source=../synthpops -m pytest -s --ignore-glob=*manual* . --junitxml=test-results.xml # Run all tests
      - name: Create coverage badge
        working-directory: ./tests
        run: coverage-badge -o coverage-badge.svg
      - name: Upload test results
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: test_results
          path: tests/test-results.xml
      - name: Upload report
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: report
          path: tests/unittests/regression/report/
      - uses: iterative/setup-cml@v1
        with:
          version: latest 
      - name: cml_run
        working-directory: ./tests
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Code coverage report
          coverage html
          echo \<p\> > report.md
          sed -n '/<table class="index">/,/<\/table>/p'  htmlcov/index.html >> report.md
          cat coverage-badge.svg >> report.md
          echo \</p\> >> report.md
          cml-send-comment report.md
          cml-send-github-check report.md
