name: Synthpops E2E workflow
on:
  workflow_dispatch:
  
  repository_dispatch:
    types: [trigger-workflow-e2e]
  schedule:
    # also run every Sunday at 0:00
    - cron:  '0 0 * * 0'  
 
  
jobs:
  install_and_test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        python-version: [ '3.8' ]
    name: Install and test e2e
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install synthpops
        run: python setup.py develop
      - name: Install tests
        run: pip install -r tests/requirements_test.txt
      - name: Run API tests
        working-directory: ./tests
        run: pytest -rfp -s e2etests --do-save --artifact-dir=artifact --workers auto > e2etest-results.txt # Run e2e tests and spit out all stdout with short summary
     
      - name: Upload test results
        uses: actions/upload-artifact@v1
        with:
          name: test_results
          path: tests/e2etest-results.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: tests/artifact/
     
          
